[ShaderOverrideUid]
hash = 8236b1752acd9b01
checktextureoverride = ib
; this fixed it????
[TextureOverrideUid]
; this one doesn't seem to do anything, but I'm leaving it here just in case
hash = 054bd731
handling = skip
[TextureOverrideUid2]
hash = 83fd403f
handling = skip
