namespace=global\yuki\debug\health

[Constants]
global $hit = 0

[Present]
post $hit = 0

; Current candidate from the old HealthBar mod.
[ShaderOverrideHealthCandidate]
hash = 000d2ce199e12697
analyse_options = dump_cb dump_tex txt
$hit = 1