; Qiqi

; Constants -------------------------

; Overrides -------------------------

[TextureOverrideQiqiPosition]
hash = cad5bebb
vb0 = ResourceQiqiPosition

[TextureOverrideQiqiBlend]
hash = cf928b89
vb1 = ResourceQiqiBlend
handling = skip
draw = 16710,0 

[TextureOverrideQiqiTexcoord]
hash = 85c5b5ed
vb1 = ResourceQiqiTexcoord

[TextureOverrideQiqiVertexLimitRaise]
hash = 956d98ae

[TextureOverrideQiqiIB]
hash = 56057a2c
handling = skip
run = CommandList\global\ORFix\ORFix
drawindexed = auto

[TextureOverrideQiqiHead]
hash = 56057a2c
match_first_index = 0
ib = ResourceQiqiHeadIB
ps-t0 = ResourceQiqiHeadLightMap
ps-t1 = ResourceQiqiHeadDiffuse


[TextureOverrideQiqiBody]
hash = 56057a2c
match_first_index = 13488
ib = ResourceQiqiBodyIB
ps-t0 = ResourceQiqiBodyLightMap
ps-t1 = ResourceQiqiBodyDiffuse


[TextureOverrideQiqiFaceHeadDiffuse]
hash = 206f5ad9
ps-t1 = ResourceQiqiFaceHeadDiffuse


; CommandList -----------------------

; Resources -------------------------

[ResourceQiqiPosition]
type = Buffer
stride = 40
filename = QiqiPosition.buf

[ResourceQiqiBlend]
type = Buffer
stride = 32
filename = QiqiBlend.buf

[ResourceQiqiTexcoord]
type = Buffer
stride = 12
filename = QiqiTexcoord.buf

[ResourceQiqiHeadIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = QiqiHead.ib

[ResourceQiqiBodyIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = QiqiBody.ib

[ResourceQiqiHeadDiffuse]
filename = QiqiHeadDiffuse.dds

[ResourceQiqiHeadLightMap]
filename = QiqiHeadLightMap.dds

[ResourceQiqiBodyDiffuse]
filename = QiqiBodyDiffuse.dds

[ResourceQiqiBodyLightMap]
filename = QiqiBodyLightMap.dds

[ResourceQiqiFaceHeadDiffuse]
filename = QiqiFaceHeadDiffuse.dds


; .ini generated by GIMI (Genshin-Impact-Model-Importer)
; If you have any issues or find any bugs, please open a ticket at https://github.com/SilentNightSound/GI-Model-Importer/issues or contact SilentNightSound#7430 on discord